### ISSUE TITLE
Reorga maxspeed

### ISSUE THREAD

**Issue by osmvermesser** [labexp/osmtracker-android#106]
hi !

to map the tag maxspeed correct there are several vales required for many countries:

missing: 20,40,70,90 no more maxspeed (look http://www.strassenschilder.de/vorschriftszeichen/ende-der-geschwindigkeitsbegrenzung/)

Jan alias User:Lübeck

**Comment by nguillaumin** [comment]
Hi, sure, that's why the custom buttons layout are for so that you can customize them for your use case: https://github.com/nguillaumin/osmtracker-android/wiki/Custom-buttons-layouts

Alternatively we could add all possible buttons for all possible speed limits in the basic layout, but I'm not sure that would work well.

**Comment by aton1698** [comment]
Hi, with the v0.7 we intoduce a [new way](https://github.com/labexp/osmtracker-android-layouts/wiki) to download/create custom buttons layouts!
With this could be easier to have a layout to track max speeds.
@osmvermesser we will close this issue, but if you have any other, let us know.
