### ISSUE TITLE
New track button

### ISSUE THREAD

**Issue by jsavage** [labexp/osmtracker-android#115]
I am running V0.6.11 on a Samsung S6. The screen contains a list of tracks a + symbol (in a circle) and drop down menu.

The instruction at the bottom of the screen states "To record a track press **New Track**"

I assume that the + symbol is the New Track button.  Before going any further please could someone confirm this.  (I have seen apps before where buttons are missing on some platforms).

I also note that:
- if I return to the track list screen and select the + button it Stops a currently recording track before starting a new one.
- however, there does not seem to be an explicit method for stopping or pausing recording.

There may be other ways of resolving this but  I suggest changing the + symbol for a standard Button labelled "Record New Track" and that once a recording is in progress, that the label be changed to "Stop Recording".

**Comment by jidanni** [comment]
Yes I was stumped by this for several hours, never thinking that + == New Track. I wish the documentation and interface agreed with each other. Or at least everywhere the instructions say New Track, they would add a (+) after it:
```Press New Track (+)```

**Comment by nguillaumin** [comment]
I think there's a bit lof legacy there, because on older Android versions there's no (+) button, but you need to press "menu" then "New Track" button (due to layout differences between Android frameworks):

![screenshot from 2017-09-30 09-18-30](https://user-images.githubusercontent.com/762512/31047481-5bdda37e-a5c0-11e7-9213-0d2451960183.png)

The (+) button was added by a contributor a while back but I guess it wasn't realized that the help message should be changed too.

* Starting a new track while one is recording will indeed stop the current one, and start a new one.
* To stop recording or pausing you can either do a long-press on the track (when on the track list), or when on the track screen there's a small "Save" button on the top right corner.

**Comment by aton1698** [comment]
Hi! In next versions we wanna to modify the application interface, our plan is to have a process where the community can participate and make his contributions. Something like this issue!
We will have the issue in mind, thaks! :D
