### ISSUE TITLE
Is upload dependent on export?

### ISSUE THREAD

**Issue by jsavage** [labexp/osmtracker-android#117]
I recorded a track yesterday and once home I selected upload.  I checked my GPS traces on OSM this morning and this new track was not listed but in the app it was shown with what I assume to be an uploaded symbol in the track list.
So I selected export and then re-uploaded this track.  I then refreshed my gps tracks list online and it was then visible.
Please correct me if I am wrong but this experience suggests that that upload function is dependent on a previous export.  I am not sure this is what the author intended but without having seen the use cases this is guesswork.

However, as a user, I want to minimise my intereactions with an app so I would prefer to able to upload recorded tracks in one operation.

**Comment by nguillaumin** [comment]
Hm, that's weird because the upload is supposed to be independent of the export. The upload does an export internally, but [to a temporary directory](https://github.com/nguillaumin/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/activity/OpenStreetMapUpload.java#L154) that doesn't affect the "main" export function.

A possible explanation is that OSM takes some time to process uploaded traces, they're not instantly visible, maybe you didn't wait long enough?

**Comment by engineeringentropy** [comment]
I had this problem, but then granting permissions to Access/Modify/Delete files fixed it. The 'export first' advice just got the App to prompt for those permissions.
