### ISSUE TITLE
Facilitate download and installation of custom Layouts

### ISSUE THREAD

**Issue by adam3497** [labexp/osmtracker-android#119]
As @jamescr mentioned in issue #85, explain, to a person who does not have technical knowledge, how to use different Layouts sometimes can be difficult. That is why we want to add extra functionality, to facilitate the task and so anyone can do it without problems.

With the following screenshots I hope to be able to explain our proposal to implement the enhancement. 

We will change the option of **buttons presets** so that instead of opening a pop-up with the Layouts that can be activated, open a new activity, such as the one shown below.

<img src="https://github.com/LabExperimental-SIUA/osmtracker-android/blob/docu/documentaci%C3%B3n/Screenshots/buttons_presets.png?raw=true" alt="buttons presets" />

In this activity we will have three sections, the first is the Layout that comes by default in the application, the second section are the Layouts that the user have downloaded and are available for being install. The custom layouts will have emerging options, such as **update and install** and **delete** (the default layout will not have these options).  Finally, the third section consists of a **add new** button which brings us to another activity where we will be able to download new Layouts.

<img src="https://github.com/LabExperimental-SIUA/osmtracker-android/blob/docu/documentaci%C3%B3n/Screenshots/available_layouts.png?raw=true" alt="available layouts" />

This activity shows the available Layouts for download on a specified server (by default a Git Hub repository), the server must follow a structure of folders and files specified to be able to work, see more information in [Guide to create Layout](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Guide-to-create-Layouts)

When a Layout is pressed a description will be displayed in the language of the device (in case the Layout is not in the language of the device it will be given a pop-up with the available languages  for the user to select in which language the  description will be shown), the same window will show the options for download or cancel (the downloaded layout will be in the default language or the selected language by the user).

Also, in the upper right (tool bar), you will have an option to configure the server where you want to download Layouts, if it is invalid an error message will be displayed.

We will be developing this proposal in the [LabExperimental-SIUA repository](https://github.com/LabExperimental-SIUA/osmtracker-android) and then we will make a pull request.   

We have two options for storing Layouts:
- The first option is to create a new "Layouts" branch inside the **osmtracker-android** repository or on the **Fork of LabExperimental-SIUA**.
- The second option is to create a completely new repository that the community can manipulate, where the Layouts can be added by means of a Pull Request following the indications of the structure.

**Comment by jsavage** [comment]
This sounds like huge improvement .

**Comment by altaros97** [comment]
**Changes**
We already have an advance of our proposal. First we have made some changes:
1. In Buttons Presets we passed from three sections to two sections (Default Layout and Downloaded Layouts).
2. The Add new button is transferred to the upper corner right, now is an add new icon (+) (It stills with the previous functionality) this was because we want to keep app style.
3. The last is the Server Settings changed to Github Repository Settings.

**Improvements**
What I said before, the Server Settings changed to Github Repository Settings, this pop-up appears when you press the add icon (in the upper corner right in Available Layouts).

<img src="https://github.com/LabExperimental-SIUA/osmtracker-android/blob/docu/documentaci%C3%B3n/Screenshots/github_repository_settings_en.png?raw=true" height="400" width="1000">

In this window you need three params, first is the Github Username, second is the Repository Name and the last is the branch name where the layouts are storaged. 
**Important**: this must follow the [structure](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Guide-to-create-Layouts) of files and directories

In our proposal you can delete, update and install (activate) the differents layouts that you have in your phone. You are able to see and download layouts from a Github Repository, and change the repository  from where the layouts are getting in the Github Repository Settings.

You can see this changes also in the [LabExperimental fork](https://github.com/LabExperimental-SIUA/osmtracker-android/tree/develop) and we appreciate any suggestions. Soon we will make the puill request·
