### ISSUE TITLE
Button produces unknown message

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#122]
I am offline. At the top of the screen there is a button. On the button there is a square with an arrow curving upwards and to the right. If I push the button some message appears in the middle of the screen very fast and then disappears. That is all I know.

**Comment by EmmanuelAB** [comment]
Hi, this happens in the screen that appears when you tap a finished track. 
- If you hold that button, a little tooltip appears saying `Export as GPX` that is the function of that button
- The problem is that that export happens so fast that the message that appears ("Preparing export") can be barely read.

**Comment by EmmanuelAB** [comment]
A possible solution could be showing a Toast after the exporting process finishes to explain what happened.

**Comment by xsaco07** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Button produces unknown message](https://trello.com/c/90xpB1au/42-button-produces-unknown-message)

**Comment by xsaco07** [comment]
This issue was fixed in pr #229
