### ISSUE TITLE
 missing icon takes two lines perhaps

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#149]
Here we see uploaded tracks take two lines and non uploaded tracks take one line. I believe this was supposed to look different.

**Comment by jidanni** [comment]
![screenshot_20180722-073029](https://user-images.githubusercontent.com/1230959/43040852-bcd03832-8d81-11e8-9bc4-5df2df6dd03c.jpg)

**Comment by jidanni** [comment]
I am using version zero point 7

**Comment by jidanni** [comment]
I don't know. It's a ASUS ZE552KL(ZenFone3) and I have chosen large characters in Settings.

**Comment by adam3497** [comment]
Well, I think it's a design error. It may be because you are using the phone with a large text and the size of the OSMTracker texts is also a bit large (default setting).

We must bear in mind that the application was developed long ago and that the screens of cell phones have changed a lot since then.

This problem could be solved with the update v0.8 but for the moment it will continue like this.

**Comment by Binnette** [comment]
I am closing this issue as I was "maybe" fixed in version 0.8. Feel free to reopen it.
