### ISSUE TITLE
initial track name time stamp in ISO-style

### ISSUE THREAD

**Issue by PontiacCZ** [labexp/osmtracker-android#162]
As of today when one starts a new track it gets its name in form "Oct 6, 2018 08:14:24" which is exported as "Oct_6,_2018_08;14;24.gpx". But in other cases OSMTracker uses ISO-style naming - for directories and audio files.

![obrazek](https://user-images.githubusercontent.com/9153595/46799191-6d547a80-cd54-11e8-9901-264c3d37fb38.png)

Please make the initial track name consistent with this style or give us an option to switch into it.

**Comment by jjiglesiasg** [comment]
ISO Name should be the standard, in my point of view

**Comment by aton1698** [comment]
A proposal to solve this issue is using the 8601 ISO (YYYY-MM-DD for dates and hh:mm:ss for times) making the files names looks like this example:
![example](https://user-images.githubusercontent.com/26258845/58352322-6f250700-7e28-11e9-91bf-a24f0ba048b5.jpeg)
*`:` can't be used in file names


Also, to have a better order in every exported trace, could exist a default directory called `traces` in the osmtracker directory (/osmtracker/traces/) that directory could have all the folders for each exported gpx:
![example2](https://user-images.githubusercontent.com/26258845/58353221-2753af00-7e2b-11e9-960b-5e9487f6d191.jpeg)

![example3](https://user-images.githubusercontent.com/26258845/58352974-6a615280-7e2a-11e9-8957-03c61575cf7d.jpeg)

**Comment by aton1698** [comment]
About the name, the bug it's because the gpx name was changed adding something at the end of the date format (shown in the GUI), the application detectes that and use that name instead the default, that is given by fallowing an static SimpleDateFormat 
`public static final SimpleDateFormat FILENAME_FORMATTER = new SimpleDateFormat("yyyy-MM-dd_HH-mm-ss");
` (line 61 in DataHelper.java)

**Comment by soniok** [comment]
I'm using v0.7.2-beta3 and the exported GPX file is by default using ISO 8601 filename naming.
But also confirm that filename is replaced with "Oct 6, 2018 08:14:24" in the gui when editing track info but the file will still use ISO 8601 if you export it using "Oct 6, 2018 08:14:24" in dialog.

Would be good to have consistent value. Gui filename, gpx filename and metadata filename to be the same value.

**Comment by xsaco07** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use GPX name for containing directory as well](https://trello.com/c/7AjJQCN3/41-use-gpx-name-for-containing-directory-as-well)

**Comment by xsaco07** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Correct consistency of trace files names](https://trello.com/c/26vNskWm/40-correct-consistency-of-trace-files-names)

**Comment by xsaco07** [comment]
We agree with @soniok talking about the consistency of the gui and exported files name. 
We decided to incorporate the ISO 8601 also in the app gui so you can find what you expected in your file system.

**Comment by aton1698** [comment]
This issue is solved with #232
