### ISSUE TITLE
please help me, i want to use this application to record a power lines that are meters,substation and pole by having three button and use it to draw electrica distribuiton line 

### ISSUE THREAD

**Issue by yosephadane** [labexp/osmtracker-android#180]

**Comment by icrf2000** [comment]
Sounds quite straightforward. What's your problem or what doesn't work?

**Comment by yosephadane** [comment]
i want to add a button with the name meter and pole, where do i define a
new button that directly register present location meter or pole?

**Comment by jsavage** [comment]
yosephadane  - If this is for a one-off project you could use existing buttons and then edit the resulting GPX to achieve what you want to do.   

On the other hand if this is to be used a lot then I think what you are asking is for help creating custom buttons.   My understanding is that the Custom Buttons feature has been improved in the last year or so but the [documentation about Custom Buttons on the wiki](https://github.com/labexp/osmtracker-android/wiki/Custom-buttons-layouts) does not look as if it has been been updated since 2015 so I am not confident that it reflect the changes in this area.   Can anyone confirm this?

**Comment by adam3497** [comment]
@yosephadane Do you mean something like this?

![seleccion_010](https://user-images.githubusercontent.com/26634599/51404698-d13bcb80-1b19-11e9-9263-fcf19f315188.png)

**Comment by yosephadane** [comment]
yes, look like it.

**Comment by yosephadane** [comment]
tanks for your support i solve the problem

**Comment by jamescr** [comment]
> On the other hand if this is to be used a lot then I think what you are asking is for help creating custom buttons. There was a request to improve the Custom Buttons feature but the [documentation about Custom Buttons on the wiki](https://github.com/labexp/osmtracker-android/wiki/Custom-buttons-layouts) does not look as if it has been been updated since 2015 so I am not confident that this feature has yet made it into the latest version. Can anyone confirm this?

The wiki page is not updated. We weren't aware of that but we'll update it, thanks for noticing it.

**Comment by EmmanuelAB** [comment]
This issue was fixed by creating a custom layout. The wiki has already been updated. Thanks.
