### ISSUE TITLE
Must upload each track individually

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#337]
Of these two versions,
https://play.google.com/store/apps/details?id=me.guillaumin.android.osmtracker

https://play.google.com/store/apps/details?id=net.osmtracker

the newer one is missing the upload item in the main menu. To upload, one must go to each track and upload it individually for some reason.

**Comment by mfrasca** [comment]
looks like a design choice in the ux, and I would agree with it.

to upload one entry, you need to select the entry, and upload it. 
1) why do you want a button in the global ⋮ menu for uploading one entry?
2) which entry, since there isn't a thing like "the select entry"?

in the global ⋮ menu I can imagine a batch upload (upload selected items, if the concept of selected tracks were implemented in OSMTracker), or an upload all (as there is now an export all, or upload all that haven't been uploaded yet); 

IMO:
upload all is a potentially dangerous operation, I would not want it in the program;
upload selected could be interesting, but we first need to implement some "select multiple items".
