### ISSUE TITLE
Bench on left side, bench on right side

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#346]
The bench button is great. Except when you're walking along the trail and you push it, when you get back home you can't tell/remember if it was on the right side or the left side of the trail, given today's GPS accuracies.

Therefore it would be great if there was two buttons, one for the left and one for right. In fact it seems all the other items, garbage pail, street lamp, etc, I forgot, also need two buttons. 

Or maybe, tap the button and hold it and swipe to the left, or swipe to the right till it goes off the screen.

**Comment by Binnette** [comment]
Hi @jidanni,

I encourage you to fork this [repository](https://github.com/labexp/osmtracker-android-layouts) and create your own custom layout by following the [documentation](https://github.com/labexp/osmtracker-android/wiki/Custom-buttons-layouts).

Adding another level under "bench" may not suit all use cases. Also, why only do this for benches? Many other POIs can benefit from this feature. Instead of editing every button in the default layout, you could try replacing the "bench" button with two buttons: "bench on left" and "bench on right". Or setting bench as a "page" to show a new screen whith the 2 buttons left and right.

As my usage of OSMTracker is mainly for walking or biking, I usually go next to the POI before pressing the corresponding buttons. This way, the POI latitude and longitude are accurate enough to add the POI to the map when reviewing my track.

Perhaps your usage is different? Maybe you're on a bus or a passenger in a car. In that case, a custom layout like "Car passenger" might be more suitable, as you can also prioritize some POIs that are easier to see when you're in a car moving at 50 km/h.

I close the bug for now. But feel free to reopen it, continue this conversation, share your usage and so on 😊👍

**Comment by Binnette** [comment]
Related to #201
