### ISSUE TITLE
Cannot be installed on Google Pixel 7

### ISSUE THREAD

**Issue by himslm01** [labexp/osmtracker-android#354]
According to Google Play Store, OSMTracker for Android "isn't compatible" with a Google Pixel 7 (Android 13).
More specifically "This app isn't available for your device because it was made for an older version of Android".
I was looking forward to using OSMTracker for Android because it's highly recommended.

**Comment by SomeoneElseOSM** [comment]
I suspect that the developers are well aware of the issue here (Google have changed how external storage is handled in Android).  See also https://github.com/labexp/osmtracker-android/issues/259 for a previous iteration.

If it helps, I have OsmTracker for Android installed on Android 13 (Nokia X10, installed while Android was < 13), and it says in Debug info:

    Environment.getExtrernalStorageDirectory: '/storage/emulated/0'
    Environment.getExternalStorageState: 'mounted'
    Can write to external storage: false

**Comment by nickstuaw** [comment]
Another outdated alert appeared for me on my new Xiaomi Redmi Note 12. My android version is 13.![Screenshot_2023-08-17-18-08-35-539_com.android.vending-edit.jpg](https://github.com/labexp/osmtracker-android/assets/90180047/8b42a9aa-da99-4977-a342-1641d60949d1)

**Comment by BinoyKadakkal** [comment]
I do have the same problem

**Comment by rummyr** [comment]
Can't install on pixel 6 with Android 13

**Comment by jamescr** [comment]
Version 2024.07.09 solved this issue.
