### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by matheusmoreira** [labexp/osmtracker-android#356]
Is this project still being maintained?

**Comment by icrf2000** [comment]
My impression is: Rather no, it is quiet. I have an own fork which has features that I love and which have never been integrated into upstream. I don't have the motivation to keep it in sync and mergeable with upstream anymore. Next time I will have to touch it is when I get a Pixel 7.

**Comment by jamescr** [comment]
> Is this project still being maintained?

Very little. 

I have been maintaining the project for the last few years (4 years perhaps), but I do it with the support of university student assistants. However, I'm having difficulty maintaining OSMTracker. The project does not have collaborators that support the project on a constant basis, the student assistants that I involve naturally rotate because they finish their studies. Additionally, in the last year it has been difficult for me to collaborate due to a personal situation (now overcome). In the next few months I will try to update the application so as not to lose it.
