### ISSUE TITLE
Upload failure on Marshmallow

### ISSUE THREAD

**Issue by begbiemark** [labexp/osmtracker-android#68]
When I touch the button to upload a track to Openstreetmap, the app instead performs an address search and then shows the map at 0.00 lat by 0.00 long.  I am using an SGS 7 Edge running Marshmallow.

**Comment by nguillaumin** [comment]
Hi, any chance you could take a few screenshots?

**Comment by begbiemark** [comment]
Sorry for the delay.  However, I don't know how much use they will be TBH.

Go into the track list
![2016-04-11 19 29 11](https://cloud.githubusercontent.com/assets/18376447/14540050/190b3686-027b-11e6-8d8a-c62a606d5c14.png)

Open a track
![2016-04-11 19 29 29](https://cloud.githubusercontent.com/assets/18376447/14540092/4752fe3e-027b-11e6-8f3f-2e6b7a13681d.png)

Touch on 'MORE' and then 'OpenStreetMap upload' in the drop-down menu
![2016-04-11 19 30 51](https://cloud.githubusercontent.com/assets/18376447/14540117/5fc2294a-027b-11e6-8779-2104364d7cb6.png)

Once tagged, touch 'SAVE AND UPLOAD'
![2016-04-11 19 31 04](https://cloud.githubusercontent.com/assets/18376447/14540139/79a1ba38-027b-11e6-8411-1d537a8cf3e4.png)

Then get taken to a map with a pin at 0 Lat by 0 Long
![2016-04-11 19 31 10](https://cloud.githubusercontent.com/assets/18376447/14540160/8eb32dbc-027b-11e6-8164-cc8c8220136e.png)

Info screen for version
![2016-04-11 19 32 32](https://cloud.githubusercontent.com/assets/18376447/14540168/984f1476-027b-11e6-8cff-b7f2d8de7e7c.png)

**Comment by begbiemark** [comment]
I realised that I don't remember OSMTracker ever asking me for my OSM credentials since installing on my new phone with Marshmallow.  I uninstalled and reinstalled just to see, and sure enough no request for OSM login credentials.  Curiously the Settings doesn't seem to have any option to enter these, and the option to force their re-input is greyed out.
![2016-04-14 19 16 46](https://cloud.githubusercontent.com/assets/18376447/14540836/00e1bbf8-027f-11e6-909e-e188a0ebff37.png)

**Comment by nguillaumin** [comment]
Thanks, that's odd. The "reset" menu is greyed out if credentials are not already stored so that makes sense, but I'm not sure why it doesn't prompt you for them. I think other people are using it successfully on Marshmallow so I'm not sure what's different here.

Unfortunately that will probably be difficult to reproduce if it only happens with this specific phone model or something. Do you think you'd be able to install the dev tools and run the app through the debugger?

**Comment by begbiemark** [comment]
Hi there, 

Can give the Feb tools a go, but you'll need to point me to some instructions. 

Is there any way to force the app to request credentials when there are none stored?

Out of curiosity, when should it have asked for them? 

Thanks, 

M

On 15 April 2016 10:41:39 BST, nguillaumin <notifications@github.com> wrote:
>Thanks, that's odd. The "reset" menu is greyed out if credentials are
>not already stored so that makes sense, but I'm not sure why it doesn't
>prompt you for them. I think other people are using it successfully on
>Marshmallow so I'm not sure what's different here.
>
>Unfortunately that will probably be difficult to reproduce if it only
>happens with this specific phone model or something. Do you think you'd
>be able to install the dev tools and run the app through the debugger?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nguillaumin/osmtracker-android/issues/68#issuecomment-210387860

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nguillaumin** [comment]
Hi,

It's not the best time for me as I'm in the middle of an overseas relocation and it's actually been a while since I used the tools, so I won't be able to give detailed instructions but you can try to start from there: http://developer.android.com/sdk/index.html

Perhaps the easiest thing to start with is to [install the command line tools](http://developer.android.com/sdk/index.html#downloads) and use `adb logcat` to display the logs while the app is running on your phone.

> Is there any way to force the app to request credentials when there are none stored?

That's the thing, it's already supposed [to do that](https://github.com/nguillaumin/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/activity/OpenStreetMapUpload.java#L137)

> Out of curiosity, when should it have asked for them?

When you press the "Save & upload" button it's supposed to check if you have a token and a secret, and if one of them is missing it's supposed to ask them again (as per the line of code above)

Nico

**Comment by chillly** [comment]
No prompt for osmid for me either. G. nexus 6p with Marshmallow

**Comment by begbiemark** [comment]
SOLVED. 

The problem is to do with the way Marshmallow is handling default actions. When paying the upload button, OSMTracker passes an OSM URL for checking credentials. However, Marshmallow in its infinite wisdom decides it knows better and uses OSMAnd to handle the link. Not surprisingly, OSMAnd had no idea what to do with it. 

The solution is to clear the actions OSMAnd is used as default for, you will then be presented with the option to authenticate. 

Sadly it seems in Marshmallow you need to go in and clear defaults for apps, then specifically tell the OS to ask each time. Otherwise the default is to act as if an invisible "always take this action" button is ticked the first time you select a particular app to handle an event. 

On 15 April 2016 13:26:15 BST, nguillaumin <notifications@github.com> wrote:
>Hi,
>
>It's not the best time for me as I'm in the middle of an overseas
>relocation and it's actually been a while since I used the tools, so I
>won't be able to give detailed instructions but you can try to start
>from there: http://developer.android.com/sdk/index.html
>
>Perhaps the easiest thing to start with is to [install the command line
>tools](http://developer.android.com/sdk/index.html#downloads) and use
>`adb logcat` to display the logs while the app is running on your
>phone.
>
>> Is there any way to force the app to request credentials when there
>are none stored?
>
>That's the thing, it's already supposed [to do
>that](https://github.com/nguillaumin/osmtracker-android/blob/master/app/src/main/java/me/guillaumin/android/osmtracker/activity/OpenStreetMapUpload.java#L137)
>
>> Out of curiosity, when should it have asked for them?
>
>When you press the "Save & upload" button it's supposed to check if you
>have a token and a secret, and if one of them is missing it's supposed
>to ask them again (as per the line of code above)
>
>Nico
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nguillaumin/osmtracker-android/issues/68#issuecomment-210445446

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by crazycaveman** [comment]
I am able to replicate this on Lollipop, 5.1.1, with my LG Leon. From what I can tell, it is due to the fact that OSMAnd advertises that it can handle OSM URIs (it has done this for some time) and, if you tell it to always open those URIs, you'll encounter this bug. It might be that Marshmallow makes it less clear that you are making it always be the default. Would using a webview in OSMTracker help fix this issue?

**Comment by nguillaumin** [comment]
Thanks guys that's a nice finding.

I think I can pinpoint it in OsmAnd in this file: https://github.com/osmandapp/Osmand/blob/d9f7ac5a50d90e4175322939ecad615dc4b0f634/OsmAnd/AndroidManifest.xml#L220

As I understand it it's for OsmAnd to open when somebody clicks on an OpenStreetMap link, to display the map in OsmAnd rather than in the browser. The problem I believe is that capturing URLs on the host only is a bit too broad as it will also capture OpenStreetMap URLs that don't point to a map, such as `/oauth/` and others (e.g. `/api/`, etc.)

A good fix I believe would be to narrow down the intent filter in OsmAnd to what OsmAnd is really interested it (I assume only displaying a map). CC'ing some OsmAnd contributors to see if that would work? @vshcherb ?

**Comment by begbiemark** [comment]
I've now learned that it's not Marshmallow per see, that was the cause. But rather that Samsung has taken out the option to choose once or always when you open a link type for the first time. So I had no idea Osmand had been set as default for these links and was therefore being selected as handler. 

So a big "thank you" to Samsung. If I wanted to be treated like a simpleton, I'd be on iOS :-) 

On 18 May 2016 23:30:23 BST, nguillaumin <notifications@github.com> wrote:
>Thanks guys that's a nice finding.
>
>I think I can pinpoint it in OsmAnd in this file:
>https://github.com/osmandapp/Osmand/blob/d9f7ac5a50d90e4175322939ecad615dc4b0f634/OsmAnd/AndroidManifest.xml#L220
>
>As I understand it it's for OsmAnd to open when somebody clicks on an
>OpenStreetMap link, to display the map in OsmAnd rather than in the
>browser. The problem I believe is that capturing URLs on the host only
>is a bit too broad as it will also capture OpenStreetMap URLs that
>don't point to a map, such as `/oauth/` and others (e.g. `/api/`, etc.)
>
>A good fix I believe would be to narrow down the intent filter in
>OsmAnd to what OsmAnd is really interested it (I assume only displaying
>a map). CC'ing some OsmAnd contributors to see if that would work?
>@vshcherb ?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nguillaumin/osmtracker-android/issues/68#issuecomment-220177558

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
