### ISSUE TITLE
Enable Android "Share" functionality so that GPX can be emailed (feature)

### ISSUE THREAD

**Issue by bjohas** [labexp/osmtracker-android#69]
Would it be possible to add an "export to gpx and share" option to the contextual menu for tracks (alongside "export to gpx")? (It could just be called "Share" with a prompt to save GPX first if needed.)

We'd like to use osmtracker for non-experts to map their educational institutions, and there needs to be a simple way for them to transfer the data. Saving as GPX, and then locating the track using a "file explorer" isn't really an option, as many services may not have that software and storage locations may differ.

It wouldn't matter if only the GPX track is shared (if that makes it easier), though sharing of all media could be possible as well.

**Comment by Nokta-strigo** [comment]
I'm working on it. In my commit e819c4d536f4c45ff0ec0fdd911b3293f05120b9 there's a menu option "Share as GPX", that saves temporary gpx file without media and sends it to another application. Tested it with gmail app.
Things I'm going to do:
- improve intent settings so that other mapping applications can receive it too.
- add option to share gpx with media. I think it will be packing the gpx with media to archive and then sharing the archive.

What are the other apps that should be able to receive gpx files?

**Comment by Gnurfos** [comment]
> What are the other apps that should be able to receive gpx files?
Thanks for the effort, I don't know how/if the intent differs from that for gmail, but personally I'd be interested in sharing to cloud saving apps (ex: dropbox, owncloud)

**Comment by Nokta-strigo** [comment]
It's not different for owncloud, and for dropbox it should work too (I'll test it later). But it may differ for geo-data related applications, I suppose. Because they may have more narrow intent filters then general-purpose file sharing applications like e-mail apps, dropbox, owncloud, etc.

**Comment by bjohas** [comment]
@Nokta-strigo - thanks for the work on this - much appreciated!

**Comment by Nokta-strigo** [comment]
Created pull request #103, waiting for @nguillaumin  :-)
