### ISSUE TITLE
Add more custom buttons layouts

### ISSUE THREAD

**Issue by Nokta-strigo** [labexp/osmtracker-android#83]
Put several button layout XMLs for typical usages into OSMTracker distro. So that one can get more comfortable layout for his needs without having to create an XML file, putting files somewhere, etc.
Typical usages:
1) _Cycling_ - more buttons for mapping cycling infrastructure, different way types, etc.
2) _Highway mapping_ - more buttons with road signs, restrictions, etc.
3) Other ideas on typical usages?

I can create and commit the _cycling_ layout and, may be, the "_highway mapping_" layout.

**Comment by steve8x8** [comment]
I'd like to chime in: It would be extremely nice if there was a way to reference the "builtin" layouts from a custom one, *without* switching.
This way, I could have my own "root" layout first, but use features of the builtin one (targetlayout="builtin:root"? this is asking for namespaces, it seems) without having to rewrite anything.

**Comment by EmmanuelAB** [comment]
in recent versions (0.7 and later) a new feature addressing this task was introduced. Now the app lets you download new layouts with one click. Just go to `Settings > ButtonsPresets > +` and you'll see a list of all available custom layouts. By the way the layouts listed in the app are consulted from [this repository](https://github.com/labexp/osmtracker-android-layouts/). You can also make your own custom layout (following [this structure](https://github.com/labexp/osmtracker-android-layouts/wiki)) and upload (via PR) it to that repository in order to make it available for everyone. 
This issue will be closed.
